[project]
name = "leitmotif"

version = "0.3.3"

description = "Discovering Leitmotifs in Multidimensional Time Series"
readme = "README.md"
authors = [
    {name = "patrickzib", email = "patrick.schaefer@hu-berlin.de"}
]
keywords = [
    "multidimensional",
    "sub-dimensional",
    "multivariate",
    "time-series",
    "motif",
    "motif-set",
    "leitmotif",
    "machine-learning",
    "motif-discovery",
    "unsupervised",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]
requires-python = ">=3.9"
dependencies = [
    "joblib>=1.2.0",
    "numba>=0.57.0",
    "numpy>=1.23.0",
    "pandas>=1.5.0",
    "psutil>=5.9.0",
    "scikit-learn>=1.1.0",
    "scipy>=1.9.0,<2.0.0",
    "seaborn>=0.12.0",
    "tqdm>=4.64.0",
    "matplotlib>=3.6.0",
    "tsdownsample>=0.1.3",
    "stumpy>=1.12.0"
]

[project.optional-dependencies]
audio = [
    "audioread>=3.0.0",
    "librosa>=0.10.0",
    "pydub>=0.25.1",
    "pylrc",
]
motion = [
    "transforms3d>=0.4.1",
]
runners = [
    "audioread>=3.0.0",
    "librosa>=0.10.0",
    "pydub>=0.25.1",
    "pylrc",
    "transforms3d>=0.4.1",
]

[project.urls]
repository = "https://github.com/patrickzib/leitmotifs"
#documentation = ""
#download = ""

[project.license]
file = "LICENSE"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]
include = ["leitmotifs*"]
exclude = ["tests", "tests.*"]

[tool.setuptools.package-data]
leitmotifs = [
    "*.csv",
    "*.csv.gz",
    "*.arff",
    "*.arff.gz",
    "*.txt",
    "*.ts",
    "*.tsv",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
